# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 585)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("python.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(22, 24, 33);\n"
"border-radius: 5px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(570, 498))
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color:rgb(22, 24, 33);\n"
"    border-radius: 5px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_17.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setMinimumSize(QtCore.QSize(48, 0))
        self.frame_11.setStyleSheet("background-color: rgb(22, 24, 33);\n"
"border-radius: 5px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame = QtWidgets.QFrame(self.frame_11)
        self.frame.setMinimumSize(QtCore.QSize(51, 18))
        self.frame.setMaximumSize(QtCore.QSize(25, 16777215))
        self.frame.setStyleSheet("background-color: #161821;\n"
"border-right: 1px solid rgb(19, 28, 35);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 8)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setMinimumSize(QtCore.QSize(49, 32))
        self.toolButton.setStyleSheet("border-style: none;\n"
"border-bottom: 1px solid rgb(19, 28, 35);\n"
"background-color: rgb(22, 24, 33);")
        self.toolButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("python_Csc_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(35, 35))
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_7.addWidget(self.toolButton)
        self.pushButton_22 = QtWidgets.QPushButton(self.frame)
        self.pushButton_22.setMinimumSize(QtCore.QSize(49, 46))
        self.pushButton_22.setMaximumSize(QtCore.QSize(200, 46))
        self.pushButton_22.setStyleSheet("QPushButton{\n"
"background-color: #161821;\n"
"background-image: url(\"filet.png\");\n"
"    color: rgb(39, 57, 71);\n"
"font-size: 16px;\n"
"border-style: none;\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:hover{\n"
" background: #1d2028;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
" border-left: 3px solid  rgb(128, 214, 197);\n"
"border-image: url(:file_hover.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:selected{\n"
" border-left: 3px solid  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(3, 167, 255, 255), stop:1 rgba(199, 255, 248, 255));;\n"
"}")
        self.pushButton_22.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_22.setIcon(icon2)
        self.pushButton_22.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_7.addWidget(self.pushButton_22)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(18, 46))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 46))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: #161821;\n"
"background-image: url(\"filet.png\");\n"
"    color: rgb(39, 57, 71);\n"
"font-size: 16px;\n"
"border-style: none;\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:hover{\n"
" background: #1d2028;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
" border-left: 3px solid  rgb(128, 214, 197);\n"
"border-image: url(:file_hover.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:selected{\n"
" border-left: 3px solid  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(3, 167, 255, 255), stop:1 rgba(199, 255, 248, 255));;\n"
"}")
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("filet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("filet.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("file_hover.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("file_hover.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("file_hover.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("file_hover.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 46))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 46))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: #161821;\n"
"background-image: url(\"filet.png\");\n"
"    color: rgb(39, 57, 71);\n"
"font-size: 16px;\n"
"border-style: none;\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:hover{\n"
" background: #1d2028;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
" border-left: 3px solid  rgb(128, 214, 197);\n"
"border-image: url(:file_hover.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:selected{\n"
" border-left: 3px solid  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(3, 167, 255, 255), stop:1 rgba(199, 255, 248, 255));;\n"
"}")
        self.pushButton_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("f9bb81e576c1a361c61a8c08945b2c48-search-icon-by-vexels.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_7.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(49, 46))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 46))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: #161821;\n"
"background-image: url(\"filet.png\");\n"
"    color: rgb(39, 57, 71);\n"
"font-size: 16px;\n"
"border-style: none;\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:hover{\n"
" background: #1d2028;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
" border-left: 3px solid  rgb(128, 214, 197);\n"
"border-image: url(:file_hover.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:selected{\n"
" border-left: 3px solid  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(3, 167, 255, 255), stop:1 rgba(199, 255, 248, 255));;\n"
"}")
        self.pushButton_3.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_7.addWidget(self.pushButton_3)
        self.pushButton_23 = QtWidgets.QPushButton(self.frame)
        self.pushButton_23.setMinimumSize(QtCore.QSize(49, 46))
        self.pushButton_23.setMaximumSize(QtCore.QSize(200, 46))
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"background-color: #161821;\n"
"background-image: url(\"filet.png\");\n"
"    color: rgb(39, 57, 71);\n"
"font-size: 16px;\n"
"border-style: none;\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:hover{\n"
" background: #1d2028;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
" border-left: 3px solid  rgb(128, 214, 197);\n"
"border-image: url(:file_hover.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:selected{\n"
" border-left: 3px solid  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(3, 167, 255, 255), stop:1 rgba(199, 255, 248, 255));;\n"
"}")
        self.pushButton_23.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("store.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_23.setIcon(icon6)
        self.pushButton_23.setIconSize(QtCore.QSize(37, 37))
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_7.addWidget(self.pushButton_23)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setMinimumSize(QtCore.QSize(49, 46))
        self.pushButton_8.setMaximumSize(QtCore.QSize(200, 46))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color: #161821;\n"
"background-image: url(\"filet.png\");\n"
"    color: rgb(39, 57, 71);\n"
"font-size: 16px;\n"
"border-style: none;\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:hover{\n"
" background: #1d2028;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
" border-left: 3px solid  rgb(128, 214, 197);\n"
"border-image: url(:file_hover.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:selected{\n"
" border-left: 3px solid  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(3, 167, 255, 255), stop:1 rgba(199, 255, 248, 255));;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_7.addWidget(self.pushButton_8)
        spacerItem = QtWidgets.QSpacerItem(15, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 46))
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 46))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: #161821;\n"
"background-image: url(\"filet.png\");\n"
"    color: rgb(39, 57, 71);\n"
"font-size: 16px;\n"
"border-style: none;\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:hover{\n"
" background: #1d2028;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
" border-left: 3px solid  rgb(128, 214, 197);\n"
"border-image: url(:file_hover.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:selected{\n"
" border-left: 3px solid  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(3, 167, 255, 255), stop:1 rgba(199, 255, 248, 255));;\n"
"}")
        self.pushButton_4.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("acc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon7)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_7.addWidget(self.pushButton_4)
        self.pushButton_24 = QtWidgets.QPushButton(self.frame)
        self.pushButton_24.setMinimumSize(QtCore.QSize(49, 46))
        self.pushButton_24.setMaximumSize(QtCore.QSize(200, 46))
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"background-color: #161821;\n"
"background-image: url(\"filet.png\");\n"
"    color: rgb(39, 57, 71);\n"
"font-size: 16px;\n"
"border-style: none;\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:hover{\n"
" background: #1d2028;\n"
"border-radius: 5px;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
" border-left: 3px solid  rgb(128, 214, 197);\n"
"border-image: url(:file_hover.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QPushButton:selected{\n"
" border-left: 3px solid  qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(3, 167, 255, 255), stop:1 rgba(199, 255, 248, 255));;\n"
"}")
        self.pushButton_24.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_24.setIcon(icon8)
        self.pushButton_24.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_7.addWidget(self.pushButton_24)
        self.horizontalLayout_18.addWidget(self.frame)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_11)
        self.frame_6.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_6.setStyleSheet("border-bottom: 1px solid rgb(19, 28, 35);\n"
"background-color: rgb(22, 24, 33);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.frame_11)
        self.frame_3.setMinimumSize(QtCore.QSize(140, 26))
        self.frame_3.setMaximumSize(QtCore.QSize(140, 16777215))
        self.frame_3.setStyleSheet("border-bottom: 1px solid rgb(19, 28, 35);\n"
"background-color: rgb(22, 24, 33);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setMinimumSize(QtCore.QSize(43, 0))
        self.pushButton_7.setMaximumSize(QtCore.QSize(43, 28))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(29, 42, 51);\n"
"}")
        self.pushButton_7.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("minimize_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon9)
        self.pushButton_7.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(43, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(43, 28))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(29, 42, 51);\n"
"}")
        self.pushButton_5.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("maximize_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon10)
        self.pushButton_5.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setMinimumSize(QtCore.QSize(43, 24))
        self.pushButton_6.setMaximumSize(QtCore.QSize(43, 28))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(128, 214, 197);\n"
"}")
        self.pushButton_6.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon11)
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame_7 = QtWidgets.QFrame(self.frame_11)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 22))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 22))
        self.frame_7.setStyleSheet("border-radius:0px;\n"
"background-color: rgb(31, 32, 44,.6);\n"
"border-bottom: 1px solid rgb(17, 24, 29);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_11.setContentsMargins(3, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setMinimumSize(QtCore.QSize(0, 16))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_8.setStyleSheet("border-style:none;\n"
"")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.pushButton_32 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_32.setStyleSheet("border-style:none;\n"
"color: rgb(40, 91, 103);")
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_11.addWidget(self.pushButton_32)
        self.toolButton_2 = QtWidgets.QToolButton(self.frame_7)
        self.toolButton_2.setStyleSheet("border-style:none;")
        self.toolButton_2.setText("")
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_11.addWidget(self.toolButton_2)
        self.verticalLayout.addWidget(self.frame_7)
        self.splitter = QtWidgets.QSplitter(self.frame_11)
        self.splitter.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName("splitter")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(156, 0))
        self.tabWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_2.setStyleSheet("QTabBar::scroller {width: 50px;}\n"
"QTabBar QToolButton::left-arrow {\n"
"border-style: none;\n"
"background: rgb(111, 160, 203);\n"
"height: 15px;\n"
"border-radius: 7px;\n"
"}\n"
"QTabBar QToolButton::right-arrow {\n"
"border-style: none;\n"
"background: rgb(17, 25, 30);\n"
"height: 15px;\n"
"border-radius: 4px;\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: none;\n"
"  background-color:#1e1f2b;\n"
"    border-right: 1px solid rgb(19, 28, 35);\n"
"    text-align: left;\n"
"    top: 0px;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255));\n"
"  padding: 7px 20px;\n"
" }\n"
"QTabBar::tab:hover {\n"
"  background-color:#1e1f2b;\n"
"    font-size: 10px;\n"
" }\n"
"\n"
"\n"
" QTabBar::tab:selected {\n"
" background-color:#1e1f2b;\n"
"    border-right: 0px solid rgb(19, 28, 35);\n"
"color: rgb(173, 202, 234);\n"
" }\n"
"QTabWidget::pane { \n"
"border-right: 1px solidrgb(255, 255, 255);\n"
"   border: none;\n"
"    border-top: 30px solid #1e1f2b;\n"
"    position: absolute;\n"
"    top: -30px;\n"
"    background: rgba( 0, 0, 0, 40% ); /* For transparent background */\n"
"}\n"
"QTabBar::close-button{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(3, 167, 255, 255), stop:1 rgba(199, 255, 248, 255));\n"
"    border-radius: 8px;\n"
"}\n"
"QTabBar {\n"
"    border-right: 1px solid rgb(216, 216, 216);\n"
"}")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setUsesScrollButtons(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("background-color:#1e1f2b;\n"
"border-right: 1px solid rgb(19, 28, 35);\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.frame_12 = QtWidgets.QFrame(self.tab_3)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 38))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 38))
        self.frame_12.setStyleSheet("background-color: rgb(128, 214, 197);\n"
"border-radius: 0px;\n"
"border-style: none;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_19.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_7 = QtWidgets.QLabel(self.frame_12)
        self.label_7.setStyleSheet("color: rgb(40, 42, 58);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_19.addWidget(self.label_7)
        self.pushButton_39 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_39.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_39.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_39.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_39.setStyleSheet("color: rgb(40, 42, 58);\n"
"font: 8pt \"MS Sans Serif\";\n"
"border-style: none;\n"
"border-radius: 3px;")
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_19.addWidget(self.pushButton_39)
        self.verticalLayout_3.addWidget(self.frame_12)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(69, 0))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(51, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"    background-color: rgb(38, 56, 70);\n"
"   border: 1px solid gray;\n"
"\n"
"}\n"
"QTabBar::scroller {width: 40px;\n"
"    border-style:none;\n"
"    background: none;\n"
"    border-radius: 10px;\n"
"    min-height: 20px;\n"
"}\n"
"QTabBar QToolButton {\n"
"    background-color: rgba(255, 255, 255);\n"
"    border:0;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"}\n"
"QTabBar QToolButton {\n"
"    background-color: rgb(26, 37, 47,.3);\n"
"    border:0;\n"
"}\n"
"QTabBar QToolButton::left-arrow:enabled {  \n"
"    background-color: rgb(26, 37, 47,.3);\n"
"    border:0;\n"
"    border-radius: 10px;\n"
"    height: 20px;\n"
"}\n"
"QTabBar QToolButton::right-arrow:enabled {   \n"
"    background-color: rgb(26, 37, 47,.3);\n"
"    border:0;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-style: none;\n"
"  background-color:#282a3a;\n"
"    text-align: left;\n"
"    top: 0px;\n"
"    color: rgb(115, 129, 136);\n"
"  padding: 8px 32px;\n"
" }\n"
"QTabBar::tab:hover {\n"
"  background-color: rgb(38, 56, 70);\n"
"    font-size: 10px;\n"
"    border-right: 0px solid rgb(42, 64, 76);\n"
"    margin: 0px -10px;\n"
" }\n"
"\n"
"\n"
" QTabBar::tab:selected {\n"
"  background-color:#282a3a;\n"
"  border-top: 1.2px solid rgb(128, 214, 197);\n"
"    \n"
"    color: rgb(128, 214, 197);\n"
"    border-bottom-left-radius: 0px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    margin: 0px -2px;\n"
" }\n"
"QTabBar::tab:selected {\n"
"  background-color:#282a3a;\n"
"  border-top: 1.2px solid rgb(128, 214, 197);\n"
"    border-right: 0px;\n"
"    border-right: 0px solid rgb(42, 64, 76);\n"
"    \n"
"    color: rgb(128, 214, 197);\n"
"    border-bottom-left-radius: 0px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    margin: 0px -2px;\n"
" }\n"
"QTabWidget::pane { \n"
"border-right: 1px solidrgb(255, 255, 255);\n"
"   border: none;\n"
"    border-top: 33px solid #282a3a;;\n"
"    position: absolute;\n"
"    top: -33px;\n"
"    background: rgba( 0, 0, 0, 40% ); /* For transparent background */\n"
"}\n"
"QTabBar::close-button{\n"
"    \n"
"    background-color: rgb(97, 110, 127);\n"
"    image:url(:cil-x.png);\n"
"    border-radius: 8px;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right; \n"
"    width: 13px;\n"
"    height: 13px;\n"
"}")
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("background-color:#282a3a;")
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.page)
        self.frame_8.setMinimumSize(QtCore.QSize(1, 23))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 23))
        self.frame_8.setStyleSheet("border-radius:0px;\n"
"border-bottom: 1px solid rgb(19, 28, 35,.3);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_31 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_31.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButton_31.setMaximumSize(QtCore.QSize(60, 35))
        self.pushButton_31.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    background-color:#282a3a;\n"
"    color: rgb(93, 178, 197);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    \n"
"    background-color: rgb(33, 49, 60);\n"
"    color: rgb(42, 91, 93);\n"
"}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_13.addWidget(self.pushButton_31)
        self.pushButton_30 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_30.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_30.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pushButton_30.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    background-color:#282a3a;\n"
"    color: rgb(93, 178, 197);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: none;\n"
"    \n"
"    background-color: rgb(33, 49, 60);\n"
"    color: rgb(42, 91, 93);\n"
"}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_13.addWidget(self.pushButton_30)
        spacerItem2 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setMinimumSize(QtCore.QSize(0, 13))
        self.label.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.pushButton_16 = QtWidgets.QPushButton(self.page)
        self.pushButton_16.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_16.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    background-color:#282a3a;\n"
"    color: rgb(59, 85, 108);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    border: 4px solid rgb(54, 78, 98);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(21, 32, 38);\n"
"    color: rgb(128, 214, 197);\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_4.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.page)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_17.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    background-color:#282a3a;\n"
"    color: rgb(59, 85, 108);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    border: 4px solid rgb(54, 78, 98);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(21, 32, 38);\n"
"    color: rgb(128, 214, 197);\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_4.addWidget(self.pushButton_17)
        self.pushButton_13 = QtWidgets.QPushButton(self.page)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_13.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    background-color:#282a3a;\n"
"    color: rgb(59, 85, 108);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    border: 4px solid rgb(54, 78, 98);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(21, 32, 38);\n"
"    color: rgb(128, 214, 197);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_4.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.page)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_14.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    background-color:#282a3a;\n"
"    color: rgb(59, 85, 108);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    border: 4px solid rgb(54, 78, 98);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(21, 32, 38);\n"
"    color: rgb(128, 214, 197);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_4.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.page)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    background-color:#282a3a;\n"
"    color: rgb(59, 85, 108);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    border: 4px solid rgb(54, 78, 98);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(21, 32, 38);\n"
"    color: rgb(128, 214, 197);\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_4.addWidget(self.pushButton_15)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setStyleSheet("color: rgb(44, 63, 80);\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(14, 0))
        self.tab.setStyleSheet("background-color: rgb(40, 42, 58);\n"
"font-size: 20px;")
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setContentsMargins(5, 0, 0, 3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 320))
        self.frame_4.setStyleSheet("border-style: none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMaximumSize(QtCore.QSize(200, 200))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("python_3.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"border-style:none;\n"
"}\n"
"\n"
"    QScrollBar::handle:horizontal {\n"
"        \n"
"    background-color: rgb(82, 120, 150);\n"
"        width: 25px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        height: 25px;\n"
"    }")
        self.textEdit.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit.setReadOnly(True)
        self.textEdit.setOverwriteMode(True)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 2, 111, 21))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"font-size: 12x;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 35, 45);\n"
"}\n"
"QPushButton:hover{\n"
"    font-size: 12x;\n"
"    color: rgb(128, 214, 197);\n"
"    background-color: rgb(26, 38, 48);\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_10.setGeometry(QtCore.QRect(120, 2, 111, 21))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"font-size: 12x;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 35, 45);\n"
"}\n"
"QPushButton:hover{\n"
"    font-size: 12x;\n"
"    color: rgb(128, 214, 197);\n"
"    background-color: rgb(26, 38, 48);\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_11.setGeometry(QtCore.QRect(240, 2, 111, 21))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"font-size: 12x;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 35, 45);\n"
"}\n"
"QPushButton:hover{\n"
"    font-size: 12x;\n"
"    color: rgb(128, 214, 197);\n"
"    background-color: rgb(26, 38, 48);\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_12.setGeometry(QtCore.QRect(360, 2, 111, 21))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"font-size: 12x;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 35, 45);\n"
"}\n"
"QPushButton:hover{\n"
"    font-size: 12x;\n"
"    color: rgb(128, 214, 197);\n"
"    background-color: rgb(26, 38, 48);\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_2.addWidget(self.frame_5)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("python.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap("acc.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon12, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_18.setGeometry(QtCore.QRect(410, 170, 115, 30))
        self.pushButton_18.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_18.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(68, 100, 124);\n"
"font-size: 14px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(19, 28, 35);\n"
"\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_19.setGeometry(QtCore.QRect(440, 270, 115, 30))
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_19.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(68, 100, 124);\n"
"font-size: 14px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(19, 28, 35);\n"
"\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_20.setGeometry(QtCore.QRect(440, 340, 115, 30))
        self.pushButton_20.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_20.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(68, 100, 124);\n"
"font-size: 14px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(19, 28, 35);\n"
"\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_21.setGeometry(QtCore.QRect(550, 390, 115, 30))
        self.pushButton_21.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_21.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(68, 100, 124);\n"
"font-size: 14px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(19, 28, 35);\n"
"\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_27.setGeometry(QtCore.QRect(230, 220, 32, 32))
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(68, 100, 124);\n"
"font-size: 14px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(19, 28, 35);\n"
"\n"
"}")
        self.pushButton_27.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("cil-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_27.setIcon(icon13)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_28.setGeometry(QtCore.QRect(270, 250, 32, 32))
        self.pushButton_28.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(68, 100, 124);\n"
"font-size: 14px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(19, 28, 35);\n"
"\n"
"}")
        self.pushButton_28.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("cil-3d.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_28.setIcon(icon14)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_29.setGeometry(QtCore.QRect(310, 290, 32, 32))
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(68, 100, 124);\n"
"font-size: 14px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(19, 28, 35);\n"
"\n"
"}")
        self.pushButton_29.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("cil-link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_29.setIcon(icon15)
        self.pushButton_29.setObjectName("pushButton_29")
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setStyleSheet("background-color: rgb(39, 57, 71);")
        self.page_6.setObjectName("page_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(200, 200))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_25 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_25.setMinimumSize(QtCore.QSize(0, 29))
        self.pushButton_25.setStyleSheet("background-color: rgb(106, 205, 207);\n"
"border-radius: 10px;")
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_6.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_26.setMinimumSize(QtCore.QSize(0, 29))
        self.pushButton_26.setStyleSheet("background-color: rgb(74, 146, 147);\n"
"border-radius: 10px;")
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_6.addWidget(self.pushButton_26)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.label_5 = QtWidgets.QLabel(self.page_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.page_4)
        self.scrollArea.setMinimumSize(QtCore.QSize(170, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(170, 16777215))
        self.scrollArea.setStyleSheet("QScollArea{\n"
"    border-style: none;\n"
"}\n"
"QScrollBar::sub-page{\n"
"        background: none;\n"
"        border-style: none;\n"
"        }\n"
"        QScrollBar::add-page:vertical {\n"
"        border-style: none;\n"
"        background:none;\n"
"        }\n"
"       QScrollBar:vertical {\n"
"            border-style: none;\n"
"          border: 0px solid #999999;\n"
"           background: rgb(39, 57, 70);\n"
"           width:10px;\n"
"           margin: 0px 0px 0px 0px;\n"
"          border-radius: 4px;\n"
"\n"
"        }\n"
"           QScrollBar::handle:vertical { \n"
"           min-height: 0px;\n"
"               border: 0px solid red;\n"
"               border-radius: 2px;\n"
"        \n"
"               background-color:rgb(39, 57, 70);\n"
"          }\n"
"         QScrollBar::add-line:vertical {      \n"
"              height: 0px;\n"
"              subcontrol-position: bottom;\n"
"               subcontrol-origin: margin;\n"
"                }\n"
"               QScrollBar::sub-line:vertical {\n"
"                    height: 0 px;\n"
"                    subcontrol-position: top;\n"
"                    subcontrol-origin: margin;\n"
"               }")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 153, 302))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: rgb(22, 24, 33);")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_34 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_34.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_34.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_34.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(46, 67, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(50, 91, 81);\n"
"    background-color: rgb(17, 25, 30);\n"
"\n"
"}")
        self.pushButton_34.setObjectName("pushButton_34")
        self.verticalLayout_5.addWidget(self.pushButton_34)
        self.pushButton_33 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_33.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_33.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_33.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(46, 67, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(50, 91, 81);\n"
"    background-color: rgb(17, 25, 30);\n"
"\n"
"}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.verticalLayout_5.addWidget(self.pushButton_33)
        self.pushButton_35 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_35.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_35.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_35.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(46, 67, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(50, 91, 81);\n"
"    background-color: rgb(17, 25, 30);\n"
"\n"
"}")
        self.pushButton_35.setObjectName("pushButton_35")
        self.verticalLayout_5.addWidget(self.pushButton_35)
        self.pushButton_37 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_37.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_37.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_37.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(46, 67, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(50, 91, 81);\n"
"    background-color: rgb(17, 25, 30);\n"
"\n"
"}")
        self.pushButton_37.setObjectName("pushButton_37")
        self.verticalLayout_5.addWidget(self.pushButton_37)
        self.pushButton_38 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_38.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_38.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_38.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(46, 67, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(50, 91, 81);\n"
"    background-color: rgb(17, 25, 30);\n"
"\n"
"}")
        self.pushButton_38.setObjectName("pushButton_38")
        self.verticalLayout_5.addWidget(self.pushButton_38)
        self.pushButton_36 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_36.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_36.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_36.setStyleSheet("QPushButton{\n"
"border-style: none;\n"
"color: rgb(46, 67, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(50, 91, 81);\n"
"    background-color: rgb(17, 25, 30);\n"
"\n"
"}")
        self.pushButton_36.setObjectName("pushButton_36")
        self.verticalLayout_5.addWidget(self.pushButton_36)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_13.addLayout(self.verticalLayout_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_8.addWidget(self.scrollArea)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_10 = QtWidgets.QFrame(self.page_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.frame_10)
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.comboBox_2 = QtWidgets.QComboBox(self.page_7)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 28))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.comboBox_2.setStyleSheet("border-style: none;\n"
"border: 1px solid rgb(50, 91, 92);\n"
"border-radius: 5px;\n"
"background-color: rgb(30, 31, 43);\n"
"color: rgb(38, 67, 83);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.verticalLayout_14.addWidget(self.comboBox_2)
        self.comboBox = QtWidgets.QComboBox(self.page_7)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 28))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.comboBox.setStyleSheet("border-style: none;\n"
"border: 1px solid rgb(50, 91, 92);\n"
"border-radius: 5px;\n"
"background-color: rgb(30, 31, 43);\n"
"color: rgb(38, 67, 83);")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_14.addWidget(self.comboBox)
        self.stackedWidget_3.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget_3.addWidget(self.page_8)
        self.gridLayout.addWidget(self.stackedWidget_3, 0, 1, 1, 1)
        self.horizontalLayout_14.addWidget(self.frame_10)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 22))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border-style: none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(31, 46, 56);\n"
"    font-size: 12px;\n"
"    border-radius: 10px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_10.addWidget(self.lineEdit)
        self.frame_2 = QtWidgets.QFrame(self.page_5)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.verticalLayout_10.addWidget(self.frame_2)
        self.stackedWidget_2.addWidget(self.page_5)
        self.verticalLayout.addWidget(self.splitter)
        self.frame_9 = QtWidgets.QFrame(self.frame_11)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_9.setStyleSheet("background-color: rgb(22, 24, 33);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.progressBar = QtWidgets.QProgressBar(self.frame_9)
        self.progressBar.setMinimumSize(QtCore.QSize(100, 12))
        self.progressBar.setMaximumSize(QtCore.QSize(100, 12))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    color: rgb(22, 24, 33);\n"
"    text-align: center;\n"
"    border-style: none;\n"
"    border-radius: 5px;\n"
"    background-color:rgb(22, 24, 33);\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 5px;\n"
"    background-color:rgb(113, 214, 197);\n"
"\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_15.addWidget(self.progressBar)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addWidget(self.frame_9)
        self.horizontalLayout_12.addLayout(self.verticalLayout)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_17.addWidget(self.frame_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMinimumSize(QtCore.QSize(100, 23))
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 32))
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusbar.setToolTip("")
        self.statusbar.setStatusTip("")
        self.statusbar.setWhatsThis("")
        self.statusbar.setAccessibleName("")
        self.statusbar.setAccessibleDescription("")
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setStyleSheet("background-color:rgb(22, 24, 33);\n"
"color: rgb(217, 217, 217);\n"
"border-top: 1px solid rgb(9, 14, 17);\n"
"border-bottom: qlineargradient(spread:pad, x1:0.488, y1:0, x2:0.5, y2:0.682, stop:0 rgba(24, 27, 40, 255), stop:1 rgba(58, 77, 95, 255));\n"
"border-radius: 3px;\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"\n"
"  min-height: 22.3px;\n"
"  font-size: 10pt;")
        self.statusbar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 613, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setMinimumSize(QtCore.QSize(90, 25))
        self.menubar.setMaximumSize(QtCore.QSize(613, 29))
        self.menubar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menubar.setStyleSheet("QMenuBar{\n"
"top: 20px;\n"
"color: rgb(124, 178, 225);\n"
"background-color: rgb(22, 24, 33);\n"
"font-size: 13px;\n"
"font-family: arial;\n"
"border-radius: 3px;\n"
"border-bottom: 1px solid rgb(9, 14, 17);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"height:15px;\n"
"\n"
"\n"
"}\n"
"QMenu {\n"
"   /* background-color: #0F7070;*/\n"
"    background-color: rgb(17, 25, 30);\n"
"    border-style:none;\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-right:none;        \n"
"    font-size: 8.5px;\n"
"    menu-scrollable: 1;\n"
"    color: rgb(124, 178, 225);\n"
"}\n"
"QMenu::item{\n"
"    \n"
"    background-color: rgb(22, 24, 33);\n"
"\n"
"}\n"
"\n"
"QMenuBar::icon{\n"
"    width: 20px;\n"
"    height: 25px;\n"
"}\n"
"QMenuBar::item {\n"
"padding: 5.45px 7px;\n"
"height:29px;\n"
"width: 35px;\n"
" }\n"
"QMenuBar::item:pressed{\n"
"background-color: rgb(40, 42, 58);\n"
"    color: rgb(85, 165, 166);\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-bottom:none;\n"
"}\n"
"QMenuBar::item:selected {\n"
"background-color:  rgb(40, 42, 58);\n"
"    color: rgb(85, 165, 166);\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-bottom:none;\n"
"}\n"
"QMenu::item {\n"
"    spacing: 3px; /* spacing between menu bar items */\n"
"    padding: 7px 30px 10px 20px;\n"
"    background: transparent;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color:  rgb(40, 42, 58);\n"
"    color: rgb(85, 165, 166);\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-bottom:none;\n"
"    background-color: rgb(29, 42, 53);\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setGeometry(QtCore.QRect(267, 149, 267, 510))
        self.menuFile.setStyleSheet("QWidget{\n"
"background-color: #b1c5e3;\n"
"}\n"
"QMenu {\n"
"   /* background-color: #0F7070;*/\n"
"    background-color: rgb(40, 42, 58);\n"
"    border-style:none;\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-right:none;        \n"
"    font-size: 8.5px;\n"
"    menu-scrollable: 1;\n"
"    color: rgb(124, 178, 225);\n"
"}\n"
"QMenuBar::item{\n"
"top: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(24, 174, 255);\n"
"}\n"
"QMenu::separator {\n"
"     height: 1.4px;\n"
"    background-color: rgb(79, 116, 144);\n"
"    border-radius: 1px;\n"
"    margin: 2px 14px;\n"
" }\n"
"\n"
"QMenu::item {\n"
"    spacing: 3px; /* spacing between menu bar items */\n"
"    padding: 7px 30px 10px 20px;\n"
"    background: transparent;\n"
"}\n"
"/*Does not work*/\n"
"QMenu::item:selected {\n"
"    background-color: rgb(31, 33, 45);\n"
"    color: rgb(85, 165, 166);\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-bottom:none;\n"
"}")
        self.menuFile.setSeparatorsCollapsible(True)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menuFile)
        self.menuSetting.setStyleSheet("QMenu {\n"
"   /* background-color: #0F7070;*/\n"
"    background-color: rgb(39, 57, 71);\n"
"    border-style:none;\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-right:none;        \n"
"    font-size: 8.5px;\n"
"    menu-scrollable: 1;\n"
"    color: rgb(124, 178, 225);\n"
"}\n"
"QMenuBar::item{\n"
"top: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(24, 174, 255);\n"
"}\n"
"QMenu::separator {\n"
"     height: 1.4px;\n"
"    background-color: rgb(79, 116, 144);\n"
"    border-radius: 1px;\n"
"    margin: 2px 14px;\n"
" }\n"
"\n"
"QMenu::item {\n"
"    spacing: 3px; /* spacing between menu bar items */\n"
"    padding: 7px 30px 10px 20px;\n"
"    background: transparent;\n"
"}\n"
"/*Does not work*/\n"
"QMenu::item:selected {\n"
"    background-color: rgb(52,73,94);\n"
"    color: rgb(85, 165, 166);\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-bottom:none;\n"
"    background-color: rgb(29, 42, 53);\n"
"}")
        self.menuSetting.setObjectName("menuSetting")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setGeometry(QtCore.QRect(302, 149, 274, 330))
        self.menuEdit.setStyleSheet("QWidget{\n"
"background-color: #b1c5e3;\n"
"}\n"
"QMenu {\n"
"   /* background-color: #0F7070;*/\n"
"    background-color: rgb(40, 42, 58);\n"
"    border-style:none;\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-right:none;        \n"
"    font-size: 8.5px;\n"
"    menu-scrollable: 1;\n"
"    color: rgb(124, 178, 225);\n"
"}\n"
"QMenuBar::item{\n"
"top: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(24, 174, 255);\n"
"}\n"
"QMenu::separator {\n"
"     height: 1.4px;\n"
"    background-color: rgb(79, 116, 144);\n"
"    border-radius: 1px;\n"
"    margin: 2px 14px;\n"
" }\n"
"\n"
"QMenu::item {\n"
"    spacing: 3px; /* spacing between menu bar items */\n"
"    padding: 7px 30px 10px 20px;\n"
"    background: transparent;\n"
"}\n"
"/*Does not work*/\n"
"QMenu::item:selected {\n"
"    background-color: rgb(31, 33, 45);\n"
"    color: rgb(85, 165, 166);\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-bottom:none;\n"
"}")
        self.menuEdit.setObjectName("menuEdit")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setStyleSheet("QWidget{\n"
"background-color: #b1c5e3;\n"
"}\n"
"QMenu {\n"
"   /* background-color: #0F7070;*/\n"
"    background-color: rgb(40, 42, 58);\n"
"    border-style:none;\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-right:none;        \n"
"    font-size: 8.5px;\n"
"    menu-scrollable: 1;\n"
"    color: rgb(124, 178, 225);\n"
"}\n"
"QMenuBar::item{\n"
"top: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(24, 174, 255);\n"
"}\n"
"QMenu::separator {\n"
"     height: 1.4px;\n"
"    background-color: rgb(79, 116, 144);\n"
"    border-radius: 1px;\n"
"    margin: 2px 14px;\n"
" }\n"
"\n"
"QMenu::item {\n"
"    spacing: 3px; /* spacing between menu bar items */\n"
"    padding: 7px 30px 10px 20px;\n"
"    background: transparent;\n"
"}\n"
"/*Does not work*/\n"
"QMenu::item:selected {\n"
"    background-color: rgb(31, 33, 45);\n"
"    color: rgb(85, 165, 166);\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-bottom:none;\n"
"}")
        self.menuRun.setObjectName("menuRun")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setStyleSheet("QWidget{\n"
"background-color: #b1c5e3;\n"
"}\n"
"QMenu {\n"
"   /* background-color: #0F7070;*/\n"
"    background-color: rgb(40, 42, 58);\n"
"    border-style:none;\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-right:none;        \n"
"    font-size: 8.5px;\n"
"    menu-scrollable: 1;\n"
"    color: rgb(124, 178, 225);\n"
"}\n"
"QMenuBar::item{\n"
"top: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(24, 174, 255);\n"
"}\n"
"QMenu::separator {\n"
"     height: 1.4px;\n"
"    background-color: rgb(79, 116, 144);\n"
"    border-radius: 1px;\n"
"    margin: 2px 14px;\n"
" }\n"
"\n"
"QMenu::item {\n"
"    spacing: 3px; /* spacing between menu bar items */\n"
"    padding: 7px 30px 10px 20px;\n"
"    background: transparent;\n"
"}\n"
"/*Does not work*/\n"
"QMenu::item:selected {\n"
"    background-color: rgb(31, 33, 45);\n"
"    color: rgb(85, 165, 166);\n"
"    border-top: none;\n"
"    border-left:none;\n"
"    border-bottom:none;\n"
"}")
        self.menuView.setObjectName("menuView")
        self.menuTheme = QtWidgets.QMenu(self.menuView)
        self.menuTheme.setStyleSheet("color: rgb(255, 255, 255);")
        self.menuTheme.setObjectName("menuTheme")
        self.menuBuild = QtWidgets.QMenu(self.menubar)
        self.menuBuild.setObjectName("menuBuild")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuH_lp = QtWidgets.QMenu(self.menubar)
        self.menuH_lp.setObjectName("menuH_lp")
        self.menuG_t = QtWidgets.QMenu(self.menubar)
        self.menuG_t.setObjectName("menuG_t")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuDebug = QtWidgets.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        self.menuForum = QtWidgets.QMenu(self.menubar)
        self.menuForum.setObjectName("menuForum")
        self.menuPlugin = QtWidgets.QMenu(self.menubar)
        self.menuPlugin.setObjectName("menuPlugin")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_File_Ctrl_N = QtWidgets.QAction(MainWindow)
        self.actionOpen_File_Ctrl_N.setObjectName("actionOpen_File_Ctrl_N")
        self.actionOpen_Folder_Ctrl_Alt_N = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder_Ctrl_Alt_N.setObjectName("actionOpen_Folder_Ctrl_Alt_N")
        self.actionAdd_Tab = QtWidgets.QAction(MainWindow)
        self.actionAdd_Tab.setObjectName("actionAdd_Tab")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRemove = QtWidgets.QAction(MainWindow)
        self.actionRemove.setObjectName("actionRemove")
        self.actionFind_Place = QtWidgets.QAction(MainWindow)
        self.actionFind_Place.setObjectName("actionFind_Place")
        self.actiongo_to_line = QtWidgets.QAction(MainWindow)
        self.actiongo_to_line.setObjectName("actiongo_to_line")
        self.actionSave_Ctrl_S = QtWidgets.QAction(MainWindow)
        self.actionSave_Ctrl_S.setObjectName("actionSave_Ctrl_S")
        self.actionSave_as_Ctrl_S = QtWidgets.QAction(MainWindow)
        self.actionSave_as_Ctrl_S.setObjectName("actionSave_as_Ctrl_S")
        self.actionSave_All_Ctrl_S = QtWidgets.QAction(MainWindow)
        self.actionSave_All_Ctrl_S.setObjectName("actionSave_All_Ctrl_S")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionClose_aAll_Tab = QtWidgets.QAction(MainWindow)
        self.actionClose_aAll_Tab.setObjectName("actionClose_aAll_Tab")
        self.actionClose_Tab = QtWidgets.QAction(MainWindow)
        self.actionClose_Tab.setObjectName("actionClose_Tab")
        self.actionClose_Window = QtWidgets.QAction(MainWindow)
        self.actionClose_Window.setObjectName("actionClose_Window")
        self.actionNew_Window = QtWidgets.QAction(MainWindow)
        self.actionNew_Window.setObjectName("actionNew_Window")
        self.actionColor = QtWidgets.QAction(MainWindow)
        self.actionColor.setObjectName("actionColor")
        self.actionStylesheet = QtWidgets.QAction(MainWindow)
        self.actionStylesheet.setObjectName("actionStylesheet")
        self.actionTheme = QtWidgets.QAction(MainWindow)
        self.actionTheme.setObjectName("actionTheme")
        self.actionProject = QtWidgets.QAction(MainWindow)
        self.actionProject.setObjectName("actionProject")
        self.actionFolder = QtWidgets.QAction(MainWindow)
        self.actionFolder.setObjectName("actionFolder")
        self.actionLibrary = QtWidgets.QAction(MainWindow)
        self.actionLibrary.setObjectName("actionLibrary")
        self.actionTerminal = QtWidgets.QAction(MainWindow)
        self.actionTerminal.setObjectName("actionTerminal")
        self.actionRun_File_Ctrl_B = QtWidgets.QAction(MainWindow)
        self.actionRun_File_Ctrl_B.setObjectName("actionRun_File_Ctrl_B")
        self.actionRun_All_Ctrl_Alt_b = QtWidgets.QAction(MainWindow)
        self.actionRun_All_Ctrl_Alt_b.setObjectName("actionRun_All_Ctrl_Alt_b")
        self.menuSetting.addAction(self.actionStylesheet)
        self.menuSetting.addAction(self.actionTheme)
        self.menuSetting.addAction(self.actionProject)
        self.menuSetting.addAction(self.actionFolder)
        self.menuSetting.addAction(self.actionLibrary)
        self.menuSetting.addAction(self.actionTerminal)
        self.menuFile.addAction(self.actionOpen_File_Ctrl_N)
        self.menuFile.addAction(self.actionOpen_Folder_Ctrl_Alt_N)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAdd_Tab)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Ctrl_S)
        self.menuFile.addAction(self.actionSave_as_Ctrl_S)
        self.menuFile.addAction(self.actionSave_All_Ctrl_S)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSetting.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose_Window)
        self.menuFile.addAction(self.actionNew_Window)
        self.menuFile.addAction(self.actionClose_Tab)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionClose_aAll_Tab)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRemove)
        self.menuEdit.addAction(self.actionFind_Place)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actiongo_to_line)
        self.menuRun.addAction(self.actionRun_All_Ctrl_Alt_b)
        self.menuRun.addAction(self.actionRun_File_Ctrl_B)
        self.menuTheme.addAction(self.actionEdit)
        self.menuView.addAction(self.menuTheme.menuAction())
        self.menuView.addAction(self.actionColor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.menubar.addAction(self.menuBuild.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuG_t.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuH_lp.menuAction())
        self.menubar.addAction(self.menuForum.menuAction())
        self.menubar.addAction(self.menuPlugin.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#325b67;\">PYCOS VISUAL | CONRED STUDIO</span></p></body></html>"))
        self.pushButton_32.setText(_translate("MainWindow", "ACCOUNT"))
        self.label_7.setText(_translate("MainWindow", "LEFT BOX"))
        self.pushButton_39.setText(_translate("MainWindow", "X"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Project"))
        self.pushButton_31.setText(_translate("MainWindow", "WELCOME"))
        self.pushButton_30.setText(_translate("MainWindow", "HOME"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#364e62;\">PYCOS VISUAL</span></p></body></html>"))
        self.pushButton_16.setText(_translate("MainWindow", "LEARN CODE"))
        self.pushButton_17.setText(_translate("MainWindow", "TUTORIAL"))
        self.pushButton_13.setText(_translate("MainWindow", "BUILD A APP"))
        self.pushButton_14.setText(_translate("MainWindow", "FOLLOW"))
        self.pushButton_15.setText(_translate("MainWindow", "OPEN FILE"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">HMMM, <span style=\" color:#00557f;\">SOMETHING</span> HAVE NO<span style=\" color:#00557f;\"> HERE</span>!!</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Welcome Tutorial"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; color:#1a272f;\">WELCOME</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#1a272f;\"><br /></p></body></html>"))
        self.pushButton_9.setText(_translate("MainWindow", "Open File"))
        self.pushButton_10.setText(_translate("MainWindow", "New File"))
        self.pushButton_11.setText(_translate("MainWindow", "Save File"))
        self.pushButton_12.setText(_translate("MainWindow", "Save as"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Welcome"))
        self.pushButton_18.setText(_translate("MainWindow", "Python   "))
        self.pushButton_19.setText(_translate("MainWindow", "UTF-8   "))
        self.pushButton_20.setText(_translate("MainWindow", "Win32   "))
        self.pushButton_21.setText(_translate("MainWindow", "Spaces 4   "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#1a272f;\">ACCOUNT</span></p></body></html>"))
        self.pushButton_25.setText(_translate("MainWindow", "Sign in"))
        self.pushButton_26.setText(_translate("MainWindow", "Sign up"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#1a272f;\">Please chance sign in/ sign up</span></p><p align=\"center\"><span style=\" font-size:12pt; color:#1a272f;\">to create and log in the account</span></p><p align=\"center\"><span style=\" font-size:12pt; color:#1a272f;\">-PYCOS VISUAL-</span></p></body></html>"))
        self.pushButton_34.setText(_translate("MainWindow", "Setting"))
        self.pushButton_33.setText(_translate("MainWindow", "Themes"))
        self.pushButton_35.setText(_translate("MainWindow", "Install"))
        self.pushButton_37.setText(_translate("MainWindow", "Learn more"))
        self.pushButton_38.setText(_translate("MainWindow", "Updates"))
        self.pushButton_36.setText(_translate("MainWindow", "Editor"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Pycos Light Theme"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#1f2e38;\">WELCOM TO LIBCOS</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuTheme.setTitle(_translate("MainWindow", "Theme                            "))
        self.menuBuild.setTitle(_translate("MainWindow", "Build"))
        self.menuTool.setTitle(_translate("MainWindow", "Tools"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuH_lp.setTitle(_translate("MainWindow", "Help"))
        self.menuG_t.setTitle(_translate("MainWindow", "Goto"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuDebug.setTitle(_translate("MainWindow", "Debug"))
        self.menuForum.setTitle(_translate("MainWindow", "Forum"))
        self.menuPlugin.setTitle(_translate("MainWindow", "Plugin"))
        self.actionOpen_File_Ctrl_N.setText(_translate("MainWindow", "Open File                                   Ctrl+N"))
        self.actionOpen_Folder_Ctrl_Alt_N.setText(_translate("MainWindow", "Open Folder                             Ctrl+Alt+N"))
        self.actionAdd_Tab.setText(_translate("MainWindow", "Add Tab"))
        self.actionEdit.setText(_translate("MainWindow", "Edit                      "))
        self.actionCut.setText(_translate("MainWindow", "Cut                                                   Ctrl+X      "))
        self.actionCopy.setText(_translate("MainWindow", "Copy                                                Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste                                                Ctrl+V"))
        self.actionRedo.setText(_translate("MainWindow", "Redo                                                Ctrl+Z"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRemove.setText(_translate("MainWindow", "Remove"))
        self.actionFind_Place.setText(_translate("MainWindow", "Find/Place"))
        self.actiongo_to_line.setText(_translate("MainWindow", "go to line"))
        self.actionSave_Ctrl_S.setText(_translate("MainWindow", "Save                                           Ctrl+S"))
        self.actionSave_as_Ctrl_S.setText(_translate("MainWindow", "Save as                                      Ctrl+Shift+S"))
        self.actionSave_All_Ctrl_S.setText(_translate("MainWindow", "Save All                                     "))
        self.actionQuit.setText(_translate("MainWindow", "Exit"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionClose_aAll_Tab.setText(_translate("MainWindow", "Close All Tab"))
        self.actionClose_Tab.setText(_translate("MainWindow", "Close Tab"))
        self.actionClose_Window.setText(_translate("MainWindow", "Close Window"))
        self.actionNew_Window.setText(_translate("MainWindow", "New Window"))
        self.actionColor.setText(_translate("MainWindow", "Color"))
        self.actionStylesheet.setText(_translate("MainWindow", "Stylesheet"))
        self.actionTheme.setText(_translate("MainWindow", "Theme"))
        self.actionProject.setText(_translate("MainWindow", "Project"))
        self.actionFolder.setText(_translate("MainWindow", "Folder"))
        self.actionLibrary.setText(_translate("MainWindow", "Library"))
        self.actionTerminal.setText(_translate("MainWindow", "Terminal"))
        self.actionRun_File_Ctrl_B.setText(_translate("MainWindow", "Run File                                     Ctrl+B"))
        self.actionRun_All_Ctrl_Alt_b.setText(_translate("MainWindow", "Run All                                      Ctrl+Alt+B"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
